### PR TITLE
issue:  Fix mongodb storage driver tests

### LINKED ISSUE #22: MongoDB tests don't work
`make unit-test` command runs all unit tests. Currently, MongoDB tests are not working properly.
MongoDB depends on the docker image. But Image isn’t created anywhere. Theoretically, tests should fail but they are not.
The problem is with `os.Exit(0)`.  Even if an error happens we exit with a successful code (`0`). 
See https://github.com/hyperledger/aries-framework-go-ext/blob/main/component/storage/mongodb/mongodb_test.go#L47

What needs to be done?
* when an error happens the exit code must be greater than `0`
* docker image needs to be set up (e.g `dockertest` is preferable)

### PR DESCRIPTION
**Pull request by pfeairheller**
This PR:

- Fixes mongodb tests to fail correctly
- Switches tests to use `dockertest` and removes container from github actions.

Closes #22

Signed-off-by: Phil Feairheller <pfeairheller@gmail.com>

### CODE REVIEW

File: component/storage/mongodb/mongodb_test.go [hunk 1]
```diff
@@ -69,21 +94,7 @@ func waitForMongoDBToStart() error {
...
-		default:
-			err := db.Client().Ping(context.Background(), nil)
-			if err != nil {
-				return err
-			}
-
-			return nil
-		}
-	}
+	return db.Client().Ping(context.Background(), nil)
```
Comment (troyronda) [inline component/storage/mongodb/mongodb_test.go:97]: should you use a context with timeout here?

Comment (pfeairheller) [reply component/storage/mongodb/mongodb_test.go:97]: Sure, fixed.

**Review by soluchok — APPROVED** [review]

**Review by troyronda — APPROVED** [review]
